### ISSUE TITLE
R_zmq_poll doesn’t properly catch interrupts

### ISSUE THREAD

**Issue by flying-sheep** [snoweye/pbdZMQ#25]
it’s really weird:

when i send a keyboard interrupt while polling, it simply gets through (the R function `zmq.poll` never returns)

but when i use a `tryCatch`, the R-level warning still gets through somehow. (although the `tryCatch` also doesn’t return)

``` r
tryCatch(zmq.poll(sock, .pbd_env$ZMQ.PO$POLLIN),
         interrupt = function(c) {})
```

when sending an interrupt while polling, the handler won’t get executed for me

(it does for @takluyver though)

**Comment by snoweye** [comment]
Thanks for reporting the problem. I will check it.

**Comment by flying-sheep** [comment]
as said: this is completely weird and possibly not even a bug in here, but we have to think about the interface.
- C does errors by 1. setting `errno` and 2. returning `-1` from a function
- R works by calling `stop(...)`

so when wrapping a C API in R, we either have to
- let the `errno` and signal propagate to R level, what we do now. (where apparently it can be caught by @takluyver’s system but not mine, although we both run R 3.2.{2,3} and linux)
- convert `errno` and signal to a `stop(...)` call (while resetting `errno` and swallowing the signal)
- signal that there was an error in another way (e.g. returning a value from the function)

currently the function doesn’t do anything with `errno` and signal, which _i think_ means that R will receive the interrupt signal or `errno==EINTR` and handle it (never letting the R function return `-1`)

**Comment by snoweye** [comment]
There are two solutions I can see for now, but I prefer the second one:
- Change `warning()` to `error()` in the C code, but this may raise a deadly signal when pbdZMQ run with other pbdR packages at thousands of cores.
- Check `ret == -1` within the R function `zmq.poll()` and call `stop()` within `zmq.poll()` if an additional argument, says `.pbd_env$ZMQ.MC$stop.at.error <- TRUE`, is given to `zmq.poll()`.

I have a quick fix pushed. Let me know it the second option works for you. I have some other functions work ok in this way.

**Comment by flying-sheep** [comment]
i’ll try shortly, thanks!

just for reference: you could reproduce this and your changes fixed it on your system, right?

**Comment by flying-sheep** [comment]
sadly this does nothing for me.

as said: for me, `zmq.poll` _does not return_ and instead a uncatchable interrupt is propagated directly to the R process which then exits.

we need to do something to catch this interrupt, likely on C level.

also, with your changes i still get the warning that is sent from the C code. did you perhaps forget to `git add src/R_zmq_poll.c` before committing?

**Comment by snoweye** [comment]
That version did not change any C code. But this one does, please try the new commit again, thanks.
- `.pbd_env$ZMQ.MC` did not pass correctly via the `MC` default option, so the internal sealed one was taken. This was probably cause the bug... Anyway, I take it off.
- I change all `warning()` to `Rprintf()`, so that the warning message will not be caught inside the C code.
- I have an example in demo, named `tryCatch.r`, that can catch either `error` or `warning` correctly.

Please check and let me know if the problem goes away.
PS. No `interrupt` option in `tryCatch()`

**Comment by flying-sheep** [comment]
will do tomorrow, thanks for the hard work!

**Comment by snoweye** [comment]
I hope you get the code right. Github was crashed yesterday.

**Comment by flying-sheep** [comment]
hmm, there’s a bug:

`R_zmq_poll` returns [the same as `zmq_poll`](http://api.zeromq.org/2-1:zmq-poll#toc3), i.e.:

> the number of **zmq_pollitem_t** structures […] Upon failure, _zmq_poll()_ shall return -1

but `zmq.poll` [checks if it’s `!= 0`](https://github.com/snoweye/pbdZMQ/blob/a22ad8047d2123d2f28e61afe06074351ab6b7f6/R/R_zmq_poll.r#L130) not `== -1` to check for failure!

there are many more `ret != 0` checks that could be similarly wrong…

**Comment by flying-sheep** [comment]
there’s some weird stuff going on. if i do this and then interrupt, the interrupt handler triggers, not the error handler!

``` r
R --slave <EOF
library(pbdZMQ)
context <- zmq.ctx.new()
receiver <- zmq.socket(context, .pbd_env$ZMQ.ST$PULL)
zmq.connect(receiver, "tcp://localhost:5557")
tryCatch(zmq.poll(c(receiver), .pbd_env$ZMQ.PO$POLLIN,
                  MC = ZMQ.MC(warning.at.error = FALSE, stop.at.error = TRUE)),
         error = print,
         interrupt = print)
print("feeneesh")
EOF
^CR_zmq_poll: 4 strerror: Unterbrechung während des Betriebssystemaufrufs
<interrupt: >
[1] 1
```

but when i do it in the kernel, the error handler triggers and i can’t catch the interrupt!

```
R_zmq_poll: 4 strerror: Unterbrechung während des Betriebssystemaufrufs
[I 23:10:31.326 NotebookApp] Kernel interrupted: c4254d1c-0c02-4dbc-860f-da298747f820
<simpleError in zmq.poll(c(sockets$hb, sockets$shell, sockets$control), rep(pollin,     3), MC = ZMQ.MC(warning.at.error = FALSE, stop.at.error = TRUE)): zmq.poll fails, -1>

Execution stopped
[I 23:10:31.999 NotebookApp] KernelRestarter: restarting kernel (1/5)
```

**Comment by snoweye** [comment]
I am not sure I understand fully what is going on here or what you want. I commit a few changes.
- `warning()` does not work properly in R, I can not catch any signal from it. The previous C's warning seems possible.
- I decide to remove that `Rprintf()`, but return a 2 elements vector, then make a fake interrupt when `ret = c(-1, 4)` and `check.ctrl.c = TRUE`.
- `stop()` seems work properly in R, I can catch a signal from it.

Some tests are added to `demo/tryCatch.r`.
- I test `Rscript demo/tryCatch.r`, `R --slave < demo/tryCatch.r`, and `source("demo/tryCatch.r")` within an R section.
- The `Ctrl+C` and `stop()` seems to be able to catch.

Please check it and let me know if there are more problems.

**Comment by flying-sheep** [comment]
huh. i get:

``` r
Press Ctrl+C or Esc to stop mspoller.
^C<interrupt: >
Press Ctrl+C or Esc to stop mspoller.

Execution stopped
```

as you can see i only pressed Ctrl+C once, and the second one immediately stops

**Comment by takluyver** [comment]
I would expect that R does something similar to Python for Ctrl-C. Python installs a C-level signal handler for SIGINT which simply sets an internal flag. Then, when control returns to Python's bytecode dispatch mechanisms, that flag is checked and turned into a KeyboardInterrupt exception. So if it's interrupted while C code is running, the C function returns, but an exception will be raised when control returns to Python.

Could that make any sense of the odd behaviour we're seeing?

**Comment by flying-sheep** [comment]
yes, perfectly.

so we actually do have to install a signal handler.

@snoweye i think `check.ctrl.c` is unnecessarily complicated. but it would be great to instead have an option that
1. installs a EINTR signal handler
2. calls `zmq_poll`
3. uninstalls the handler
4. return an error code / warn / … if an interrupt was caught, as usual

if the option isn’t set, the interrupt would pass through as usual (or simply `raise(EINTR)`)

**Comment by takluyver** [comment]
Though if it's doing that, I'm still a bit confused why catching an `interrupt` condition at the R level didn't work for you - that's what worked for me.

**Comment by flying-sheep** [comment]
maybe some flag doesn’t get reset properly?

because the interrupt handler _does_ get triggered, stuff just aborts afterwards anyway (maybe in the next `zmq.poll` call? that could be it…)

**Comment by snoweye** [comment]
- `R --slave <`, `Rscript`, and `source()` act differently under my systems.
- I have poll2 functions rewritten with some internal pointers returned back to R, and simplified all poll functions to see if the problem is in `tryCatch()` or in zmq itself.
- `tryCatch()` can not capture `ctrl+c` from `zmq_poll()` since it was captured by zmq itself otherwise `c(-1, 4)` can not be returned. I doubt an additional handler will help this.
- I signal an interrupt inside `zmq.poll.interrupt()`, but not help too much.
- `Rscript demo/iter_try.r` is ok in my linux, but can return `NULL` sometime which means `ctrl+c` is neither captured by zmq nor `tryCatch()`. This is not a clear point to me where `ctrl+c` should be captured by zmq, tryCatch(), or R, e.g. I may wrap `poller` inside an R loop.
- `source("demo/iter_next.r")` and `Rscript demo/iter_next.r` is ok in my linux. No good solution for `R --slave < ...`.
- None of the above is good in windows which needs to kill pids of R manually.

**Comment by flying-sheep** [comment]
OK, i think at this point we have to redirect this to the R bugtracker and have a main R dev sort it out for us.

**Comment by snoweye** [comment]
@flying-sheep Would you mind to try [the latest update](https://github.com/snoweye/pbdZMQ/commit/87812d795be4200d88e3536a6b966bf7edc3772e) for this issue again? I have an example [check_eintr](https://github.com/snoweye/pbdZMQ/blob/master/demo/check_eintr.r) that seems ok to me in my linux vm, but not ok in my win which hangs at the poller call (I am not sure how to stop it via ctrl-c or esc yet.)

**Comment by flying-sheep** [comment]
> commit message “I want to go home.”

oh no, i’m sorry!

> Would you mind to try the latest update for this issue again?

it seems to work well! with that pbdZMQ commit, and IRkernel 0.8.9, i can finally interrupt an idle kernel without killing it!

**Comment by snoweye** [comment]
I think this was fixed, so I close this one. Let me know if there are other questions.
